-- Enriched Services with detailed descriptions and sub-services
UPDATE services SET description = 'Servizio professionale di assemblaggio computer personalizzati. Progettiamo e realizziamo workstation ad alte prestazioni per professionisti (CAD, montaggio video, rendering 3D) e PC Gaming estremi. \r\n\r\nSotto-servizi inclusi:\r\n- Scelta componenti compatibili\r\n- Cable management professionale\r\n- Installazione sistema operativo e driver\r\n- Stress-test componenti e benchmarking\r\n- Overclocking sicuro e ottimizzazione bios.' WHERE slug = 'assemblaggio-pc';

UPDATE services SET description = 'Diagnosi rapida e riparazione definitiva per notebook e PC desktop di ogni marca (HP, Dell, Lenovo, Acer, Asus). Risolviamo problemi di accensione, spegnimenti improvvisi e rallentamenti hardware.\r\n\r\nInterventi comuni:\r\n- Sostituzione Hard Disk con SSD\r\n- Riparazione cerniere e scocche notebook\r\n- Sostituzione tastiere e connettori di alimentazione\r\n- Risoluzione schermate blu (BSOD)\r\n- Sostituzione ventole e dissipatori.' WHERE slug = 'riparazione-pc';

UPDATE services SET description = 'Recupero professionale di file, foto e documenti da qualsiasi supporto danneggiato. Utilizziamo software avanzati e procedure sicure per massimizzare le probabilità di successo.\r\n\r\nSupporti supportati:\r\n- Hard Disk meccanici (rumori metallici, cadute)\r\n- SSD e memorie flash (non rilevati)\r\n- Chiavette USB e schede SD rotte o formattate\r\n- Recupero dati da NAS e sistemi RAID\r\n- Backup preventivo e soluzioni Cloud.' WHERE slug = 'recupero-dati';

UPDATE services SET description = 'Proteggi la tua identità digitale e i tuoi file. Eliminiamo virus, spyware, ransomware e ottimizziamo il tuo sistema per renderlo veloce come il primo giorno.\r\n\r\nCosa offriamo:\r\n- Rimozione profonda di malware e virus residenti\r\n- Installazione e configurazione Antivirus professionale\r\n- Pulizia file temporanei e registro di sistema\r\n- Ottimizzazione avvio e gestione risorse\r\n- Messa in sicurezza della rete Wi-Fi domestica.' WHERE slug = 'pulizia-sicurezza';

UPDATE services SET description = 'Non buttare il tuo vecchio PC, potenziarlo conviene! Upgrade mirati per estendere la vita del tuo computer di altri 4-5 anni con prestazioni raddoppiate.\r\n\r\nUpgrade disponibili:\r\n- Passaggio da HDD a SSD (Velocità +10x)\r\n- Espansione memoria RAM (Multitasking fluido)\r\n- Sostituzione scheda video (Gaming e Grafica)\r\n- Aggiornamento processore (dove possibile)\r\n- Migrazione completa dati e sistema su nuovo disco.' WHERE slug = 'upgrade-pc';

UPDATE services SET description = 'Assistenza tecnica specializzata per le console di gioco più diffuse. Risolviamo problemi hardware comuni per farti tornare a giocare il prima possibile.\r\n\r\nEsempi di intervento:\r\n- Sostituzione porta HDMI (PS4, PS5, Xbox One/Series)\r\n- Pulizia interna completa e cambio pasta termica\r\n- Riparazione lettore disco e carrello\r\n- Sostituzione analogici controller (Drifting)\r\n- Espansione memoria interna (SSD/HDD).' WHERE slug = 'riparazione-console';

UPDATE services SET description = 'Servizio rapido di riparazione hardware per dispositivi portatili. Utilizziamo ricambi di alta qualità e garantiamo test rigorosi post-riparazione.\r\n\r\nPrincipali servizi:\r\n- Sostituzione display rotto o rigato\r\n- Cambio batteria esausta o gonfia\r\n- Riparazione danni da liquido\r\n- Sostituzione scocche e vetri posteriori\r\n- Riparazione fotocamere e sensori.' WHERE slug = 'schermi-batterie';

UPDATE services SET description = 'Affidati a esperti per la gestione delle tue pratiche digitali. Ti aiutiamo a navigare nel mondo della burocrazia online con semplicità e sicurezza.\r\n\r\nSupporto per:\r\n- Attivazione e gestione SPID\r\n- Configurazione PEC (Posta Elettronica Certificata)\r\n- Installazione e uso Firma Digitale\r\n- Accesso portali INPS, Agenzia Entrate, Comune\r\n- Risoluzione problemi con browser e siti governativi.' WHERE slug = 'servizi-digitali';
